// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
var services = [
  {
    name: "Landing Page de alta convers\xE3o",
    description: "P\xE1gina \xFAnica focada em vendas, com copy persuasiva, design premium e CTA para WhatsApp.",
    prazo: "5 a 7 dias \xFAteis"
  },
  {
    name: "Site institucional",
    description: "Site de apresenta\xE7\xE3o para empresas e profissionais, com p\xE1ginas de servi\xE7os, sobre e contato.",
    prazo: "2 a 3 semanas"
  },
  {
    name: "Site para portf\xF3lio / marca pessoal",
    description: "Vitrine digital para profissionais que precisam mostrar trabalhos, autoridade e captar clientes.",
    prazo: "2 a 3 semanas"
  },
  {
    name: "Manuten\xE7\xE3o e evolu\xE7\xE3o",
    description: "30 dias de suporte gratuito ap\xF3s a entrega e pacotes mensais de manuten\xE7\xE3o e atualiza\xE7\xF5es.",
    prazo: "Cont\xEDnuo"
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "Listar servi\xE7os",
  description: "Lista os servi\xE7os de cria\xE7\xE3o de sites oferecidos por J\xF4natas Vitor, com descri\xE7\xE3o e prazo m\xE9dio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/list-portfolio.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";
var projects = [
  {
    title: "Vivendo Poderosamente",
    category: "Landing Page",
    subtitle: "Curso de transforma\xE7\xE3o pessoal",
    description: "P\xE1gina de vendas com design impactante para curso de transforma\xE7\xE3o pessoal.",
    type: "Projeto Real",
    link: "https://www.vivendopoderosamente.com.br/"
  },
  {
    title: "ViniDigital",
    category: "Site Institucional",
    subtitle: "CFTV, El\xE9trica e Automa\xE7\xE3o",
    description: "Site institucional para empresa de CFTV, El\xE9trica e Automa\xE7\xE3o com design moderno.",
    type: "Projeto Real",
    link: null
  },
  {
    title: "Cl\xEDnica do iPhone",
    category: "Site Institucional",
    subtitle: "Assist\xEAncia t\xE9cnica",
    description: "Site modelo para assist\xEAncia t\xE9cnica de iPhones com design moderno e profissional.",
    type: "Prot\xF3tipo",
    link: null
  },
  {
    title: "Beatriz",
    category: "Marca pessoal",
    subtitle: "Estrategista digital",
    description: "Site modelo para estrategista digital e mentora com design elegante e sofisticado.",
    type: "Prot\xF3tipo",
    link: null
  },
  {
    title: "CSA Engenharia",
    category: "Site Institucional",
    subtitle: "Engenharia Civil",
    description: "Site institucional para empresa de engenharia civil, com identidade s\xF3bria e foco em credibilidade.",
    type: "Prot\xF3tipo",
    link: null
  }
];
var list_portfolio_default = defineTool2({
  name: "list_portfolio",
  title: "Listar portf\xF3lio",
  description: "Lista os projetos e prot\xF3tipos de sites j\xE1 criados por J\xF4natas Vitor. Filtre por categoria se necess\xE1rio.",
  inputSchema: {
    category: z.string().trim().optional().describe("Filtro opcional por categoria, ex.: 'Landing Page'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = category ? projects.filter(
      (p) => p.category.toLowerCase().includes(category.toLowerCase())
    ) : projects;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { projects: items }
    };
  }
});

// src/lib/mcp/tools/list-faq.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var faqs = [
  {
    question: "Quanto tempo leva para criar meu site?",
    answer: "Em m\xE9dia, entrego projetos de landing page em 5-7 dias \xFAteis. Para sites mais complexos como e-commerces ou portf\xF3lios extensos, o prazo pode variar de 2-3 semanas. Sempre combinaremos um cronograma antes de iniciar."
  },
  {
    question: "O site ser\xE1 responsivo (funciona no celular)?",
    answer: "Sim! Todos os sites s\xE3o desenvolvidos com abordagem mobile-first, garantindo uma experi\xEAncia perfeita em qualquer dispositivo - smartphones, tablets e desktops."
  },
  {
    question: "Voc\xEAs oferecem suporte ap\xF3s a entrega?",
    answer: "Ofere\xE7o 30 dias de suporte gratuito ap\xF3s a entrega para ajustes e d\xFAvidas. Tamb\xE9m disponibilizo pacotes de manuten\xE7\xE3o mensal para quem precisa de atualiza\xE7\xF5es cont\xEDnuas."
  },
  {
    question: "Quais formas de pagamento s\xE3o aceitas?",
    answer: "Aceito PIX, transfer\xEAncia banc\xE1ria e cart\xE3o de cr\xE9dito (parcelado em at\xE9 12x). O pagamento \xE9 dividido: 50% para iniciar o projeto e 50% na entrega."
  },
  {
    question: "Preciso fornecer textos e imagens?",
    answer: "Idealmente sim, pois voc\xEA conhece melhor seu neg\xF3cio. Mas posso ajudar com copywriting persuasivo e indicar bancos de imagens profissionais. Tamb\xE9m trabalho com fot\xF3grafos parceiros se necess\xE1rio."
  }
];
var list_faq_default = defineTool3({
  name: "search_faq",
  title: "Buscar no FAQ",
  description: "Retorna as perguntas frequentes sobre prazos, pagamento, suporte e responsividade. Use 'query' para filtrar.",
  inputSchema: {
    query: z2.string().trim().optional().describe("Termo de busca opcional para filtrar perguntas e respostas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query?.toLowerCase();
    const items = q ? faqs.filter(
      (f) => f.question.toLowerCase().includes(q) || f.answer.toLowerCase().includes(q)
    ) : faqs;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { faqs: items }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
var contact = {
  nome: "J\xF4natas Vitor",
  atuacao: "Criador de sites de alta convers\xE3o",
  site: "https://joniisites.com.br",
  whatsapp: "+55 19 3199-0107",
  whatsapp_link: "https://wa.me/551931990107?text=Ol%C3%A1!%20Quero%20agendar%20uma%20conversa%20sobre%20cria%C3%A7%C3%A3o%20de%20sites.",
  instagram: "https://instagram.com/jonii.sites",
  observacao: "Primeira consulta gratuita. Atendimento pelo WhatsApp."
};
var get_contact_default = defineTool4({
  name: "get_contact_info",
  title: "Obter contato",
  description: "Retorna os canais de contato p\xFAblicos de J\xF4natas Vitor (WhatsApp, Instagram e site) para or\xE7amentos.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: contact
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "jonatas-vitor-sites-that-convert",
  title: "Jonatas Vitor: Sites That Convert",
  version: "0.1.0",
  instructions: "Ferramentas p\xFAblicas do site de J\xF4natas Vitor, criador de sites de alta convers\xE3o. Use `list_services` para os servi\xE7os e prazos, `list_portfolio` para projetos j\xE1 entregues, `search_faq` para d\xFAvidas sobre prazo, pagamento e suporte, e `get_contact_info` para os canais de contato (WhatsApp/Instagram).",
  tools: [list_services_default, list_portfolio_default, list_faq_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
